/*
 * MetaSV API Spec
 *
 * API definition for MetaSV provided apis
 *
 * API version: 2.1.4
 * Contact: heqiming@metasv.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metasv

import (
	"encoding/json"
)

// UserTrafficSum Summed outbound traffic for this month and lastMonth.
type UserTrafficSum struct {
	// Summed traffic for currentMonth.
	ThisMonth *int64 `json:"thisMonth,omitempty"`
	// Summed traffic for lastMonth.
	LastMonth *int64 `json:"lastMonth,omitempty"`
}

// NewUserTrafficSum instantiates a new UserTrafficSum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserTrafficSum() *UserTrafficSum {
	this := UserTrafficSum{}
	return &this
}

// NewUserTrafficSumWithDefaults instantiates a new UserTrafficSum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserTrafficSumWithDefaults() *UserTrafficSum {
	this := UserTrafficSum{}
	return &this
}

// GetThisMonth returns the ThisMonth field value if set, zero value otherwise.
func (o *UserTrafficSum) GetThisMonth() int64 {
	if o == nil || o.ThisMonth == nil {
		var ret int64
		return ret
	}
	return *o.ThisMonth
}

// GetThisMonthOk returns a tuple with the ThisMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserTrafficSum) GetThisMonthOk() (*int64, bool) {
	if o == nil || o.ThisMonth == nil {
		return nil, false
	}
	return o.ThisMonth, true
}

// HasThisMonth returns a boolean if a field has been set.
func (o *UserTrafficSum) HasThisMonth() bool {
	if o != nil && o.ThisMonth != nil {
		return true
	}

	return false
}

// SetThisMonth gets a reference to the given int64 and assigns it to the ThisMonth field.
func (o *UserTrafficSum) SetThisMonth(v int64) {
	o.ThisMonth = &v
}

// GetLastMonth returns the LastMonth field value if set, zero value otherwise.
func (o *UserTrafficSum) GetLastMonth() int64 {
	if o == nil || o.LastMonth == nil {
		var ret int64
		return ret
	}
	return *o.LastMonth
}

// GetLastMonthOk returns a tuple with the LastMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserTrafficSum) GetLastMonthOk() (*int64, bool) {
	if o == nil || o.LastMonth == nil {
		return nil, false
	}
	return o.LastMonth, true
}

// HasLastMonth returns a boolean if a field has been set.
func (o *UserTrafficSum) HasLastMonth() bool {
	if o != nil && o.LastMonth != nil {
		return true
	}

	return false
}

// SetLastMonth gets a reference to the given int64 and assigns it to the LastMonth field.
func (o *UserTrafficSum) SetLastMonth(v int64) {
	o.LastMonth = &v
}

func (o UserTrafficSum) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ThisMonth != nil {
		toSerialize["thisMonth"] = o.ThisMonth
	}
	if o.LastMonth != nil {
		toSerialize["lastMonth"] = o.LastMonth
	}
	return json.Marshal(toSerialize)
}

type NullableUserTrafficSum struct {
	value *UserTrafficSum
	isSet bool
}

func (v NullableUserTrafficSum) Get() *UserTrafficSum {
	return v.value
}

func (v *NullableUserTrafficSum) Set(val *UserTrafficSum) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTrafficSum) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTrafficSum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTrafficSum(val *UserTrafficSum) *NullableUserTrafficSum {
	return &NullableUserTrafficSum{value: val, isSet: true}
}

func (v NullableUserTrafficSum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTrafficSum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
