/*
 * MetaSV API Spec
 *
 * API definition for MetaSV provided apis
 *
 * API version: 2.1.4
 * Contact: heqiming@metasv.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metasv

import (
	"encoding/json"
)

// SensibleNftAuctionUtxo Sensible nft auction Utxo belongs to the specified address
type SensibleNftAuctionUtxo struct {
	// Address string of this utxo
	Address *string `json:"address,omitempty"`
	// Txid for this utxo.
	Txid *string `json:"txid,omitempty"`
	// Output index for the Utxo.
	TxIndex *int32 `json:"txIndex,omitempty"`
	// bidBsvPrice
	BidBsvPrice *int64 `json:"bidBsvPrice,omitempty"`
	// bidTimestamp
	BidTimestamp *int64 `json:"bidTimestamp,omitempty"`
	// bidderAddressPkh
	BidderAddressPkh *string `json:"bidderAddressPkh,omitempty"`
	// Codehash of this utxo.
	CodeHash *string `json:"codeHash,omitempty"`
	// Genesis of this utxo.
	Genesis *string `json:"genesis,omitempty"`
	// endTimestamp
	EndTimestamp *int64 `json:"endTimestamp,omitempty"`
	// feeAddressPkh
	FeeAddressPkh *string `json:"feeAddressPkh,omitempty"`
	// feeAmount
	FeeAmount *int64 `json:"feeAmount,omitempty"`
	// feeRate
	FeeRate *int32 `json:"feeRate,omitempty"`
	// The height of this utxo, -1 for unconfirmed utxo.
	Height *int32 `json:"height,omitempty"`
	// nftCodeHash
	NftCodeHash *string `json:"nftCodeHash,omitempty"`
	// nftId of the auctioning fnt
	NftId *string `json:"nftId,omitempty"`
	// senderAddressPkh
	SenderAddressPkh *string `json:"senderAddressPkh,omitempty"`
	// SensibleId of the utxo
	SensibleId *string `json:"sensibleId,omitempty"`
	// startBsvPrice
	StartBsvPrice *int64 `json:"startBsvPrice,omitempty"`
	// Bsv value of the utxo(Irrelavant to token value)
	Satoshi *int64 `json:"satoshi,omitempty"`
	// Bsv value of the utxo(In string format)
	SatoshiString *string `json:"satoshiString,omitempty"`
	// The hash160 of the script(p2ch address)
	ContractAddress *string `json:"contractAddress,omitempty"`
	// this the nft send to this contract address
	IsReady *bool `json:"isReady,omitempty"`
	// Flag used for paging
	Flag *string `json:"flag,omitempty"`
}

// NewSensibleNftAuctionUtxo instantiates a new SensibleNftAuctionUtxo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSensibleNftAuctionUtxo() *SensibleNftAuctionUtxo {
	this := SensibleNftAuctionUtxo{}
	return &this
}

// NewSensibleNftAuctionUtxoWithDefaults instantiates a new SensibleNftAuctionUtxo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSensibleNftAuctionUtxoWithDefaults() *SensibleNftAuctionUtxo {
	this := SensibleNftAuctionUtxo{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *SensibleNftAuctionUtxo) SetAddress(v string) {
	o.Address = &v
}

// GetTxid returns the Txid field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetTxid() string {
	if o == nil || o.Txid == nil {
		var ret string
		return ret
	}
	return *o.Txid
}

// GetTxidOk returns a tuple with the Txid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetTxidOk() (*string, bool) {
	if o == nil || o.Txid == nil {
		return nil, false
	}
	return o.Txid, true
}

// HasTxid returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasTxid() bool {
	if o != nil && o.Txid != nil {
		return true
	}

	return false
}

// SetTxid gets a reference to the given string and assigns it to the Txid field.
func (o *SensibleNftAuctionUtxo) SetTxid(v string) {
	o.Txid = &v
}

// GetTxIndex returns the TxIndex field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetTxIndex() int32 {
	if o == nil || o.TxIndex == nil {
		var ret int32
		return ret
	}
	return *o.TxIndex
}

// GetTxIndexOk returns a tuple with the TxIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetTxIndexOk() (*int32, bool) {
	if o == nil || o.TxIndex == nil {
		return nil, false
	}
	return o.TxIndex, true
}

// HasTxIndex returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasTxIndex() bool {
	if o != nil && o.TxIndex != nil {
		return true
	}

	return false
}

// SetTxIndex gets a reference to the given int32 and assigns it to the TxIndex field.
func (o *SensibleNftAuctionUtxo) SetTxIndex(v int32) {
	o.TxIndex = &v
}

// GetBidBsvPrice returns the BidBsvPrice field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetBidBsvPrice() int64 {
	if o == nil || o.BidBsvPrice == nil {
		var ret int64
		return ret
	}
	return *o.BidBsvPrice
}

// GetBidBsvPriceOk returns a tuple with the BidBsvPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetBidBsvPriceOk() (*int64, bool) {
	if o == nil || o.BidBsvPrice == nil {
		return nil, false
	}
	return o.BidBsvPrice, true
}

// HasBidBsvPrice returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasBidBsvPrice() bool {
	if o != nil && o.BidBsvPrice != nil {
		return true
	}

	return false
}

// SetBidBsvPrice gets a reference to the given int64 and assigns it to the BidBsvPrice field.
func (o *SensibleNftAuctionUtxo) SetBidBsvPrice(v int64) {
	o.BidBsvPrice = &v
}

// GetBidTimestamp returns the BidTimestamp field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetBidTimestamp() int64 {
	if o == nil || o.BidTimestamp == nil {
		var ret int64
		return ret
	}
	return *o.BidTimestamp
}

// GetBidTimestampOk returns a tuple with the BidTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetBidTimestampOk() (*int64, bool) {
	if o == nil || o.BidTimestamp == nil {
		return nil, false
	}
	return o.BidTimestamp, true
}

// HasBidTimestamp returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasBidTimestamp() bool {
	if o != nil && o.BidTimestamp != nil {
		return true
	}

	return false
}

// SetBidTimestamp gets a reference to the given int64 and assigns it to the BidTimestamp field.
func (o *SensibleNftAuctionUtxo) SetBidTimestamp(v int64) {
	o.BidTimestamp = &v
}

// GetBidderAddressPkh returns the BidderAddressPkh field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetBidderAddressPkh() string {
	if o == nil || o.BidderAddressPkh == nil {
		var ret string
		return ret
	}
	return *o.BidderAddressPkh
}

// GetBidderAddressPkhOk returns a tuple with the BidderAddressPkh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetBidderAddressPkhOk() (*string, bool) {
	if o == nil || o.BidderAddressPkh == nil {
		return nil, false
	}
	return o.BidderAddressPkh, true
}

// HasBidderAddressPkh returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasBidderAddressPkh() bool {
	if o != nil && o.BidderAddressPkh != nil {
		return true
	}

	return false
}

// SetBidderAddressPkh gets a reference to the given string and assigns it to the BidderAddressPkh field.
func (o *SensibleNftAuctionUtxo) SetBidderAddressPkh(v string) {
	o.BidderAddressPkh = &v
}

// GetCodeHash returns the CodeHash field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetCodeHash() string {
	if o == nil || o.CodeHash == nil {
		var ret string
		return ret
	}
	return *o.CodeHash
}

// GetCodeHashOk returns a tuple with the CodeHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetCodeHashOk() (*string, bool) {
	if o == nil || o.CodeHash == nil {
		return nil, false
	}
	return o.CodeHash, true
}

// HasCodeHash returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasCodeHash() bool {
	if o != nil && o.CodeHash != nil {
		return true
	}

	return false
}

// SetCodeHash gets a reference to the given string and assigns it to the CodeHash field.
func (o *SensibleNftAuctionUtxo) SetCodeHash(v string) {
	o.CodeHash = &v
}

// GetGenesis returns the Genesis field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetGenesis() string {
	if o == nil || o.Genesis == nil {
		var ret string
		return ret
	}
	return *o.Genesis
}

// GetGenesisOk returns a tuple with the Genesis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetGenesisOk() (*string, bool) {
	if o == nil || o.Genesis == nil {
		return nil, false
	}
	return o.Genesis, true
}

// HasGenesis returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasGenesis() bool {
	if o != nil && o.Genesis != nil {
		return true
	}

	return false
}

// SetGenesis gets a reference to the given string and assigns it to the Genesis field.
func (o *SensibleNftAuctionUtxo) SetGenesis(v string) {
	o.Genesis = &v
}

// GetEndTimestamp returns the EndTimestamp field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetEndTimestamp() int64 {
	if o == nil || o.EndTimestamp == nil {
		var ret int64
		return ret
	}
	return *o.EndTimestamp
}

// GetEndTimestampOk returns a tuple with the EndTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetEndTimestampOk() (*int64, bool) {
	if o == nil || o.EndTimestamp == nil {
		return nil, false
	}
	return o.EndTimestamp, true
}

// HasEndTimestamp returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasEndTimestamp() bool {
	if o != nil && o.EndTimestamp != nil {
		return true
	}

	return false
}

// SetEndTimestamp gets a reference to the given int64 and assigns it to the EndTimestamp field.
func (o *SensibleNftAuctionUtxo) SetEndTimestamp(v int64) {
	o.EndTimestamp = &v
}

// GetFeeAddressPkh returns the FeeAddressPkh field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetFeeAddressPkh() string {
	if o == nil || o.FeeAddressPkh == nil {
		var ret string
		return ret
	}
	return *o.FeeAddressPkh
}

// GetFeeAddressPkhOk returns a tuple with the FeeAddressPkh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetFeeAddressPkhOk() (*string, bool) {
	if o == nil || o.FeeAddressPkh == nil {
		return nil, false
	}
	return o.FeeAddressPkh, true
}

// HasFeeAddressPkh returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasFeeAddressPkh() bool {
	if o != nil && o.FeeAddressPkh != nil {
		return true
	}

	return false
}

// SetFeeAddressPkh gets a reference to the given string and assigns it to the FeeAddressPkh field.
func (o *SensibleNftAuctionUtxo) SetFeeAddressPkh(v string) {
	o.FeeAddressPkh = &v
}

// GetFeeAmount returns the FeeAmount field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetFeeAmount() int64 {
	if o == nil || o.FeeAmount == nil {
		var ret int64
		return ret
	}
	return *o.FeeAmount
}

// GetFeeAmountOk returns a tuple with the FeeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetFeeAmountOk() (*int64, bool) {
	if o == nil || o.FeeAmount == nil {
		return nil, false
	}
	return o.FeeAmount, true
}

// HasFeeAmount returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasFeeAmount() bool {
	if o != nil && o.FeeAmount != nil {
		return true
	}

	return false
}

// SetFeeAmount gets a reference to the given int64 and assigns it to the FeeAmount field.
func (o *SensibleNftAuctionUtxo) SetFeeAmount(v int64) {
	o.FeeAmount = &v
}

// GetFeeRate returns the FeeRate field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetFeeRate() int32 {
	if o == nil || o.FeeRate == nil {
		var ret int32
		return ret
	}
	return *o.FeeRate
}

// GetFeeRateOk returns a tuple with the FeeRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetFeeRateOk() (*int32, bool) {
	if o == nil || o.FeeRate == nil {
		return nil, false
	}
	return o.FeeRate, true
}

// HasFeeRate returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasFeeRate() bool {
	if o != nil && o.FeeRate != nil {
		return true
	}

	return false
}

// SetFeeRate gets a reference to the given int32 and assigns it to the FeeRate field.
func (o *SensibleNftAuctionUtxo) SetFeeRate(v int32) {
	o.FeeRate = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetHeight() int32 {
	if o == nil || o.Height == nil {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetHeightOk() (*int32, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *SensibleNftAuctionUtxo) SetHeight(v int32) {
	o.Height = &v
}

// GetNftCodeHash returns the NftCodeHash field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetNftCodeHash() string {
	if o == nil || o.NftCodeHash == nil {
		var ret string
		return ret
	}
	return *o.NftCodeHash
}

// GetNftCodeHashOk returns a tuple with the NftCodeHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetNftCodeHashOk() (*string, bool) {
	if o == nil || o.NftCodeHash == nil {
		return nil, false
	}
	return o.NftCodeHash, true
}

// HasNftCodeHash returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasNftCodeHash() bool {
	if o != nil && o.NftCodeHash != nil {
		return true
	}

	return false
}

// SetNftCodeHash gets a reference to the given string and assigns it to the NftCodeHash field.
func (o *SensibleNftAuctionUtxo) SetNftCodeHash(v string) {
	o.NftCodeHash = &v
}

// GetNftId returns the NftId field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetNftId() string {
	if o == nil || o.NftId == nil {
		var ret string
		return ret
	}
	return *o.NftId
}

// GetNftIdOk returns a tuple with the NftId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetNftIdOk() (*string, bool) {
	if o == nil || o.NftId == nil {
		return nil, false
	}
	return o.NftId, true
}

// HasNftId returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasNftId() bool {
	if o != nil && o.NftId != nil {
		return true
	}

	return false
}

// SetNftId gets a reference to the given string and assigns it to the NftId field.
func (o *SensibleNftAuctionUtxo) SetNftId(v string) {
	o.NftId = &v
}

// GetSenderAddressPkh returns the SenderAddressPkh field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetSenderAddressPkh() string {
	if o == nil || o.SenderAddressPkh == nil {
		var ret string
		return ret
	}
	return *o.SenderAddressPkh
}

// GetSenderAddressPkhOk returns a tuple with the SenderAddressPkh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetSenderAddressPkhOk() (*string, bool) {
	if o == nil || o.SenderAddressPkh == nil {
		return nil, false
	}
	return o.SenderAddressPkh, true
}

// HasSenderAddressPkh returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasSenderAddressPkh() bool {
	if o != nil && o.SenderAddressPkh != nil {
		return true
	}

	return false
}

// SetSenderAddressPkh gets a reference to the given string and assigns it to the SenderAddressPkh field.
func (o *SensibleNftAuctionUtxo) SetSenderAddressPkh(v string) {
	o.SenderAddressPkh = &v
}

// GetSensibleId returns the SensibleId field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetSensibleId() string {
	if o == nil || o.SensibleId == nil {
		var ret string
		return ret
	}
	return *o.SensibleId
}

// GetSensibleIdOk returns a tuple with the SensibleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetSensibleIdOk() (*string, bool) {
	if o == nil || o.SensibleId == nil {
		return nil, false
	}
	return o.SensibleId, true
}

// HasSensibleId returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasSensibleId() bool {
	if o != nil && o.SensibleId != nil {
		return true
	}

	return false
}

// SetSensibleId gets a reference to the given string and assigns it to the SensibleId field.
func (o *SensibleNftAuctionUtxo) SetSensibleId(v string) {
	o.SensibleId = &v
}

// GetStartBsvPrice returns the StartBsvPrice field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetStartBsvPrice() int64 {
	if o == nil || o.StartBsvPrice == nil {
		var ret int64
		return ret
	}
	return *o.StartBsvPrice
}

// GetStartBsvPriceOk returns a tuple with the StartBsvPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetStartBsvPriceOk() (*int64, bool) {
	if o == nil || o.StartBsvPrice == nil {
		return nil, false
	}
	return o.StartBsvPrice, true
}

// HasStartBsvPrice returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasStartBsvPrice() bool {
	if o != nil && o.StartBsvPrice != nil {
		return true
	}

	return false
}

// SetStartBsvPrice gets a reference to the given int64 and assigns it to the StartBsvPrice field.
func (o *SensibleNftAuctionUtxo) SetStartBsvPrice(v int64) {
	o.StartBsvPrice = &v
}

// GetSatoshi returns the Satoshi field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetSatoshi() int64 {
	if o == nil || o.Satoshi == nil {
		var ret int64
		return ret
	}
	return *o.Satoshi
}

// GetSatoshiOk returns a tuple with the Satoshi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetSatoshiOk() (*int64, bool) {
	if o == nil || o.Satoshi == nil {
		return nil, false
	}
	return o.Satoshi, true
}

// HasSatoshi returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasSatoshi() bool {
	if o != nil && o.Satoshi != nil {
		return true
	}

	return false
}

// SetSatoshi gets a reference to the given int64 and assigns it to the Satoshi field.
func (o *SensibleNftAuctionUtxo) SetSatoshi(v int64) {
	o.Satoshi = &v
}

// GetSatoshiString returns the SatoshiString field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetSatoshiString() string {
	if o == nil || o.SatoshiString == nil {
		var ret string
		return ret
	}
	return *o.SatoshiString
}

// GetSatoshiStringOk returns a tuple with the SatoshiString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetSatoshiStringOk() (*string, bool) {
	if o == nil || o.SatoshiString == nil {
		return nil, false
	}
	return o.SatoshiString, true
}

// HasSatoshiString returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasSatoshiString() bool {
	if o != nil && o.SatoshiString != nil {
		return true
	}

	return false
}

// SetSatoshiString gets a reference to the given string and assigns it to the SatoshiString field.
func (o *SensibleNftAuctionUtxo) SetSatoshiString(v string) {
	o.SatoshiString = &v
}

// GetContractAddress returns the ContractAddress field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetContractAddress() string {
	if o == nil || o.ContractAddress == nil {
		var ret string
		return ret
	}
	return *o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetContractAddressOk() (*string, bool) {
	if o == nil || o.ContractAddress == nil {
		return nil, false
	}
	return o.ContractAddress, true
}

// HasContractAddress returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasContractAddress() bool {
	if o != nil && o.ContractAddress != nil {
		return true
	}

	return false
}

// SetContractAddress gets a reference to the given string and assigns it to the ContractAddress field.
func (o *SensibleNftAuctionUtxo) SetContractAddress(v string) {
	o.ContractAddress = &v
}

// GetIsReady returns the IsReady field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetIsReady() bool {
	if o == nil || o.IsReady == nil {
		var ret bool
		return ret
	}
	return *o.IsReady
}

// GetIsReadyOk returns a tuple with the IsReady field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetIsReadyOk() (*bool, bool) {
	if o == nil || o.IsReady == nil {
		return nil, false
	}
	return o.IsReady, true
}

// HasIsReady returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasIsReady() bool {
	if o != nil && o.IsReady != nil {
		return true
	}

	return false
}

// SetIsReady gets a reference to the given bool and assigns it to the IsReady field.
func (o *SensibleNftAuctionUtxo) SetIsReady(v bool) {
	o.IsReady = &v
}

// GetFlag returns the Flag field value if set, zero value otherwise.
func (o *SensibleNftAuctionUtxo) GetFlag() string {
	if o == nil || o.Flag == nil {
		var ret string
		return ret
	}
	return *o.Flag
}

// GetFlagOk returns a tuple with the Flag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SensibleNftAuctionUtxo) GetFlagOk() (*string, bool) {
	if o == nil || o.Flag == nil {
		return nil, false
	}
	return o.Flag, true
}

// HasFlag returns a boolean if a field has been set.
func (o *SensibleNftAuctionUtxo) HasFlag() bool {
	if o != nil && o.Flag != nil {
		return true
	}

	return false
}

// SetFlag gets a reference to the given string and assigns it to the Flag field.
func (o *SensibleNftAuctionUtxo) SetFlag(v string) {
	o.Flag = &v
}

func (o SensibleNftAuctionUtxo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Txid != nil {
		toSerialize["txid"] = o.Txid
	}
	if o.TxIndex != nil {
		toSerialize["txIndex"] = o.TxIndex
	}
	if o.BidBsvPrice != nil {
		toSerialize["bidBsvPrice"] = o.BidBsvPrice
	}
	if o.BidTimestamp != nil {
		toSerialize["bidTimestamp"] = o.BidTimestamp
	}
	if o.BidderAddressPkh != nil {
		toSerialize["bidderAddressPkh"] = o.BidderAddressPkh
	}
	if o.CodeHash != nil {
		toSerialize["codeHash"] = o.CodeHash
	}
	if o.Genesis != nil {
		toSerialize["genesis"] = o.Genesis
	}
	if o.EndTimestamp != nil {
		toSerialize["endTimestamp"] = o.EndTimestamp
	}
	if o.FeeAddressPkh != nil {
		toSerialize["feeAddressPkh"] = o.FeeAddressPkh
	}
	if o.FeeAmount != nil {
		toSerialize["feeAmount"] = o.FeeAmount
	}
	if o.FeeRate != nil {
		toSerialize["feeRate"] = o.FeeRate
	}
	if o.Height != nil {
		toSerialize["height"] = o.Height
	}
	if o.NftCodeHash != nil {
		toSerialize["nftCodeHash"] = o.NftCodeHash
	}
	if o.NftId != nil {
		toSerialize["nftId"] = o.NftId
	}
	if o.SenderAddressPkh != nil {
		toSerialize["senderAddressPkh"] = o.SenderAddressPkh
	}
	if o.SensibleId != nil {
		toSerialize["sensibleId"] = o.SensibleId
	}
	if o.StartBsvPrice != nil {
		toSerialize["startBsvPrice"] = o.StartBsvPrice
	}
	if o.Satoshi != nil {
		toSerialize["satoshi"] = o.Satoshi
	}
	if o.SatoshiString != nil {
		toSerialize["satoshiString"] = o.SatoshiString
	}
	if o.ContractAddress != nil {
		toSerialize["contractAddress"] = o.ContractAddress
	}
	if o.IsReady != nil {
		toSerialize["isReady"] = o.IsReady
	}
	if o.Flag != nil {
		toSerialize["flag"] = o.Flag
	}
	return json.Marshal(toSerialize)
}

type NullableSensibleNftAuctionUtxo struct {
	value *SensibleNftAuctionUtxo
	isSet bool
}

func (v NullableSensibleNftAuctionUtxo) Get() *SensibleNftAuctionUtxo {
	return v.value
}

func (v *NullableSensibleNftAuctionUtxo) Set(val *SensibleNftAuctionUtxo) {
	v.value = val
	v.isSet = true
}

func (v NullableSensibleNftAuctionUtxo) IsSet() bool {
	return v.isSet
}

func (v *NullableSensibleNftAuctionUtxo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSensibleNftAuctionUtxo(val *SensibleNftAuctionUtxo) *NullableSensibleNftAuctionUtxo {
	return &NullableSensibleNftAuctionUtxo{value: val, isSet: true}
}

func (v NullableSensibleNftAuctionUtxo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSensibleNftAuctionUtxo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
